version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:11.15.0
    working_directory: ~/chika-component

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/chika-component

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/chika-component
          paths:
            - node_modules
  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run codecov
      - run: bash <(curl -s https://codecov.io/bash) -t 23446e71-0065-4582-b354-266b384f3625
  dist:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build
      - run: ls dist
      - run: ls dist/lib
      - run: node ./scripts/dekko-dist.js
      - persist_to_workspace:
          root: ~/chika-component
          paths:
            - dist
  compile:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run compile
      - run: ls lib
      - run: ls lib/component
      - run: node ./scripts/dekko-lib.js
      - persist_to_workspace:
          root: ~/chika-component
          paths:
            - lib
  test_dist:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          command: npm test -- -u --maxWorkers=2
          environment:
            LIB_DIR: dist
  test_lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          command: npm test -- -u --maxWorkers=2
          environment:
            LIB_DIR: lib

workflows:
  version: 2
  build:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - dist:
          requires:
            - setup
      - test:
          requires:
            - setup
      - test_dist:
          requires:
            - dist
      - lint:
          requires:
            - setup
      - compile:
          requires:
            - setup
      - test_lib:
          requires:
            - compile
